{% set name = "jupyter-fs" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 859d43f6e306932715a604cb3cf11402371f01b5fe6f2b42dbee3c9f51f9737d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - nodejs
    - pip
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
    - python {{ python_min }}
  run:
    - fs >=2.4.11
    - fs-s3fs >=1.1.1
    - fs.smbfs >=0.6.3
    - jupyterlab >=4,<5
    - jupyter_server >=2,<3
    - python >={{ python_min }}

test:
  imports:
    - jupyterfs
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/jpmorganchase/jupyter-fs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Filesystem-like multi-contents manager backend for Jupyter
  description: A Filesystem-like mult-contents manager backend for Jupyter
  dev_url: https://github.com/jpmorganchase/jupyter-fs

extra:
  recipe-maintainers:
    - vidartf
    - timkpaine
    - telamonian
