{% set name = "jupyter-fs" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 736b154a26930894d47aca03fe8f6fc45ed718a8322ed0fad4c0a641c33e56b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - nodejs
    - pip
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
    - python >=3.8
  run:
    - fs >=2.4.11
    - fs-s3fs >=1.1.1
    - jupyterlab >=4,<5
    - jupyter_server >=2,<3
    - python >=3.7

test:
  imports:
    - jupyterfs

about:
  home: http://github.com/jpmorganchase/jupyter-fs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Filesystem-like multi-contents manager backend for Jupyter

  description: |
    A Filesystem-like mult-contents manager backend for Jupyter
  dev_url: https://github.com/jpmorganchase/jupyter-fs

extra:
  recipe-maintainers:
    - vidartf
    - timkpaine
    - telamonian
